### ISSUE TITLE
instance delete - runabove

### ISSUE THREAD

**Issue by krzysztofantczak** [ovh/node-ovh#2]
Hi,

It seems that runabove response to [DELETE] /1.0/instance/INSTANCE_ID is empty and that triggers following line of code: https://github.com/ovh/node-ovh/blob/master/lib/ovh.js#L591

**Comment by gierschv** [comment]
Hi @krzysztofantczak,

Thank you for this feedback. It seems that the RA API returns a content-type "application/json" with a 0 bytes HTTP body. I'll check that with my colleagues at RunAbove and at the same time provide a fix for this case.

Cheers,
Vincent

**Comment by gierschv** [comment]
Fix available in v1.1.3 (0013dc7cfd).

**Comment by krzysztofantczak** [comment]
Thanks ;-)
