### ISSUE TITLE
is it possible to create vps via api in ovh

### ISSUE THREAD

**Issue by casha1995** [ovh/node-ovh#30]
```
Bad Request (400)
{ "message": "Custom field vps_ssd_datacenter is mandatory for product ssd_model1_2018v1\nCustom field vps_ssd_os is mandatory for product ssd_model1_2018v1" }
```

i get this error when i try to validate my shopping and create order , is there is an option to add OS in post request or it's not possible to create vps with this api ?

**Comment by rbeuque74** [comment]
Hello,
Not related to node-ovh and dupplicates https://github.com/ovh/order-cart-examples/issues/5

Closing.
