### ISSUE TITLE
API endpoints started returning 204 for No Content but client throws error

### ISSUE THREAD

**Issue by mcdado** [ovh/node-ovh#51]
The client expects response http code 200 but some endpoints (in my case domain zone refresh) started returning 204:

https://github.com/ovh/node-ovh/blob/06d61afd5e21c9872b80de2695f13ef2be1b8ae8/lib/ovh.es5.js#L197

https://github.com/ovh/node-ovh/blob/06d61afd5e21c9872b80de2695f13ef2be1b8ae8/lib/ovh.es6.js#L176

Should be `res.statusCode >= 400`

**Comment by mcdado** [comment]
I did a very quick search, didn't see that I'm referring to another call. Either way, the recently merge #50 is not published yet to npm, so the issue is still active.

**Comment by Clovel** [comment]
Yep, I don't know why they haven't published it yet. I have to wrap all my calls that can potentially return 204s until then.

**Comment by marie-j** [comment]
Package is now published under a new name (@ovhcloud/node-ovh). Patch has been included in the 3.0.0 release https://www.npmjs.com/package/@ovhcloud/node-ovh/v/3.0.0
