### ISSUE TITLE
error on npm update

### ISSUE THREAD

**Issue by miton18** [ovh/node-ovh#7]
Hi, I've just updated my project and now, something not work, on ovh module, the error is : 
  
    TypeError : Proxy.create is not a function
    refer to : ovh.js on line 226

Someone ever had this error?

**Comment by VincentCasse** [comment]
Can you send a sample of the code you use to have this error?

**Comment by miton18** [comment]
Yes, this is Coffee
  
    conf = configService.getConfig()
        unless conf.appKey
            $window.location.replace '#/connect/true'
            return
        @ovh = (require 'ovh')(conf)

and conf object:

    {"endpoint":"kimsufi-eu","appKey":"xxxx","appSecret":"xxx"}

**Comment by yadutaf** [comment]
Hi @miton18,

Did you try with node 4.4.0 LTS ? The code has not changed in a while. It seems unlikely that a regression has been introduced recently. My guess would be that the code may not be compatible with newer versions of Node. But i may be wrong.

Can you try as much as possible to use pure JS example ? This will help other people finding solutions through existing issues without learning dialects. Even though Coffee is pretty popular :)

**Comment by miton18** [comment]
OK, in reality I use Eletron atom to run my app, and yes I have downgrade Electron-prebuilt and it works, I think there are some changes in electron's node engine
Any upgrade of node-ovh will be plan?

**Comment by yadutaf** [comment]
Can you open a dedicated issue mentioning the upgrade with a plain js code sample which is broken in the upgrade ? Thanks for reporting.
